### ISSUE TITLE
[Feature] The test process takes too long.

### ISSUE THREAD

**Issue by bozihu** [shaunyuan22/SODA-mmrotate#1]
### What's the feature?

When I inference the test data, the merge process and evaluation process take too long. For example, when I use Rotated Retinanet with Res50 as backbone to test, it will cost half an hour. Please give me some advises.

**Comment by Songyeyaosong** [comment]
Hi, I have set the nproc by 24, but it seems like still only use 1 process to evaluate the iou, and it takes a lot of time to test. Could like tell me how you fix this? Thank you very much!

**Comment by Songyeyaosong** [comment]
> The evaluation process stuck in the IoU computation stage which could get worse when there are dense predictions and instances. We have already organized the codes in a multi-processing manner hence increase the args `nproc` could alleviate such situation.

Hi, I have set the nproc by 24, but it seems like still only use 1 process to evaluate the iou, and it takes a lot of time to test. Could you like tell me how can fix this? Thank you very much!

**Comment by Songyeyaosong** [comment]
> > The evaluation process stuck in the IoU computation stage which could get worse when there are dense predictions and instances. We have already organized the codes in a multi-processing manner hence increase the args `nproc` could alleviate such situation.
> 
> Hi, I have set the nproc by 24, but it seems like still only use 1 process to evaluate the iou, and it takes a lot of time to test. Could you like tell me how can fix this? Thank you very much!

Hi, I set the iou_thrs by np.array([0.5]), and it does save a lot of time!

**Comment by Songyeyaosong** [comment]
Hi, I have changed some code to solve this problem. Hope this can be helpful.#10

**Comment by Songyeyaosong** [comment]
Hi, I have changed some code to solve this problem. Hope this can be helpful.
shaunyuan22/SODA-mmrotate#7
