### ISSUE TITLE
How to train？ [Bug]

### ISSUE THREAD

**Issue by GDragon986** [shaunyuan22/SODA-mmrotate#10]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

TorchVision: 0.13.1
OpenCV: 4.8.0
MMCV: 1.5.3
MMCV Compiler: MSVC 191627049
MMCV CUDA Compiler: 11.3
MMRotate: 0.3.3+04da23d

### Reproduces the problem - code sample

python tools/train.py configs/sodaa-benchmarks/rotated_faster_rcnn_r50_fpn_1x.py

### Reproduces the problem - command or script

python tools/train.py configs/sodaa-benchmarks/rotated_faster_rcnn_r50_fpn_1x.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "F:\VirtualEnvironment\SODA_A\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() missing 1 required positional argument: 'version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 168, in main
    datasets = [build_dataset(cfg.data.train)]
  File "f:\codes\soda-mmrotate\mmrotate\datasets\builder.py", line 47, in build_dataset
    dataset = build_from_cfg(cfg, ROTATED_DATASETS, default_args)
  File "F:\VirtualEnvironment\SODA_A\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SODAADataset: __init__() missing 1 required positional argument: 'version'

### Additional information

怎么可视化数据集

**Comment by shaunyuan22** [comment]
Please upate the code `configs/_base_/datasets/sodaa.py` and `mmrotate/datasets/sodaa.py`, in which the keyword `angle_version` is identical to MMRotate.

**Comment by GDragon986** [comment]
There is no angle_version keyword in configs/_base_/datasets/sodaa.py, how do I make sure that angle_version is the same as MMRotate?

**Comment by GDragon986** [comment]
> Please upate the code `configs/_base_/datasets/sodaa.py` and `mmrotate/datasets/sodaa.py`, in which the keyword `angle_version` is identical to MMRotate.

There is no angle_version keyword in configs/base/datasets/sodaa.py, how do I make sure that angle_version is the same as MMRotate?

**Comment by shaunyuan22** [comment]
We've already updated the corresponding code, please download and replace the original codes

**Comment by GDragon986** [comment]
> We've already updated the corresponding code, please download and replace the original codes

The code has run successfully, thank you very much!

**Comment by shaunyuan22** [comment]
You're welcome :)

**Comment by shaunyuan22** [comment]
You're welcome :)
