### ISSUE TITLE
[Bug] There is a lag when performing the assessment, it stays stuck in place.

### ISSUE THREAD

**Issue by Alexwong-1024** [shaunyuan22/SODA-mmrotate#13]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

The environment you require.

### Reproduces the problem - code sample

                                                  ] 0/30974, elapsed: 0s, ETA:/root/miniconda3/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_head.py:123: UserWarning: DeprecationWarning: anchor_generator is deprecated, please use "prior_generator" instead
  warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
[>>>>>>>>>>>>>>>>>>>>>>>] 30974/30974, 17.6 task/s, elapsed: 1757s, ETA:     0s
>>> Merge detected results of patch for whole image evaluating...
00002
00106
00335
00602
00187
00081
00421
00213
00798
00547
00576
00651
00251
00457
00330
00138
00735
00782
00264
00070
00146
00362
00657
00465
00399
00738

### Reproduces the problem - command or script

python tools/test.py   /SODA-mmrotate/configs/sodaa-benchmarks/oriented_rcnn_r50_fpn_1x.py --checkpoint
/SODA-mmrotate/work_dirs/oriented-rcnn-r50/epoch_1.pth
--eval
mAP

### Reproduces the problem - error message

warnings.warn('DeprecationWarning: anchor_generator is deprecated, '
[>>>>>>>>>>>>>>>>>>>>>>>] 30974/30974, 17.6 task/s, elapsed: 1757s, ETA:     0s
>>> Merge detected results of patch for whole image evaluating...
00002
00106
00335
00602
00187
00081
00421
00213
00798
00547
00576
00651
00251
00457
00330
00138
00735
00782
00264
00070
00146
00362
00657
00465
00399
00738

There is a lag when performing the assessment, it stays stuck in place, looking forward to your response author.

### Additional information

The dataset is the SODA-A

**Comment by shaunyuan22** [comment]
From our past testing experiences, it seems that the issue is tied to the hardware environment. Try to turn off the multi-processing during merging the results by set `nproc` for merge with 0

**Comment by chnu-cpl** [comment]
> From our past testing experiences, it seems that the issue is tied to the hardware environment. Try to turn off the multi-processing during merging the results by set `nproc` for merge with 0

Hello, I've encountered the same issue before. Could you please tell me how to set the nproc for merging to 0? I've tried testing it again after restarting my computer, but it still gets stuck. My computer hardware includes a 3090 graphics card and 48GB of RAM.
