### ISSUE TITLE
[Bug] have error after 1 epoch train

### ISSUE THREAD

**Issue by LW091** [shaunyuan22/SODA-mmrotate#14]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmrotate

### Environment

as same as the paper

### Reproduces the problem - code sample

ValueError: not enough values to unpack (expected 2, got 0)

### Reproduces the problem - command or script

python tools/train.py configs/sodaa-benchmarks/rotated_faster_rcnn_r50_fpn_1x.py

### Reproduces the problem - error message

completed: 0, elapsed: 0sTraceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 187, in main
    train_detector(
  File "/root/autodl-fs/SODA-A/mmrotate/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 63, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 367, in evaluate
    eval_res = self.dataloader.dataset.evaluate(
  File "/root/autodl-fs/SODA-A/mmrotate/mmrotate/datasets/sodaa.py", line 412, in evaluate
    merged_results = self.merge_det(results, nproc=nproc)
  File "/root/autodl-fs/SODA-A/mmrotate/mmrotate/datasets/sodaa.py", line 268, in merge_det
    dets, segms = results
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by shaunyuan22** [comment]
Are there any elements in the results?

**Comment by LW091** [comment]
Looks like a problem with the data set. I've fixed it. But I have a question, which configuration file was used for the test? Is it a cfinet‘s config profile? But this project doesn't have that model.Maybe sodaa-benchmarks/rotated_faster_rcnn_r50_fpn_1x.py?

**Comment by LW091** [comment]
I do not know that soda-a dataset how to test.take it to the CFINet? maybe just change the dataset?

**Comment by shaunyuan22** [comment]
When you want to implement CFINet on SODA-A dataset, except change the dataset, the CRPN codes could be directly transfered to here while the implementation of FIHead needs to be aligned with OBB RoIHead, please refer to this [issue](https://github.com/shaunyuan22/CFINet/issues/10).

**Comment by printer878** [comment]
I meet the same question, could you tell me more details about how did you resolve the question? Thank you.

> Looks like a problem with the data set. I've fixed it. But I have a question, which configuration file was used for the test? Is it a cfinet‘s config profile? But this project doesn't have that model.Maybe sodaa-benchmarks/rotated_faster_rcnn_r50_fpn_1x.py?

**Comment by printer878** [comment]
I meet the same question, could you tell me more details about how did you resolve the question? Thank you.

> ### Prerequisite
> * [x]  I have searched [Issues](https://github.com/open-mmlab/mmrotate/issues) and [Discussions](https://github.com/open-mmlab/mmrotate/discussions) but cannot get the expected help.
> * [x]  I have read the [FAQ documentation](https://mmrotate.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
> * [x]  The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmrotate) or [latest version (1.x)](https://github.com/open-mmlab/mmrotate/tree/dev-1.x).
> 
> ### Task
> I'm using the official example scripts/configs for the officially supported tasks/models/datasets.
> 
> ### Branch
> master branch https://github.com/open-mmlab/mmrotate
> 
> ### Environment
> as same as the paper
> 
> ### Reproduces the problem - code sample
> ValueError: not enough values to unpack (expected 2, got 0)
> 
> ### Reproduces the problem - command or script
> python tools/train.py configs/sodaa-benchmarks/rotated_faster_rcnn_r50_fpn_1x.py
> 
> ### Reproduces the problem - error message
> completed: 0, elapsed: 0sTraceback (most recent call last): File "tools/train.py", line 198, in main() File "tools/train.py", line 187, in main train_detector( File "/root/autodl-fs/SODA-A/mmrotate/mmrotate/apis/train.py", line 141, in train_detector runner.run(data_loaders, cfg.workflow) File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run epoch_runner(data_loaders[i], **kwargs) File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 58, in train self.call_hook('after_train_epoch') File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook getattr(hook, fn_name)(self) File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch self._do_evaluate(runner) File "/root/miniconda3/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 63, in _do_evaluate key_score = self.evaluate(runner, results) File "/root/miniconda3/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 367, in evaluate eval_res = self.dataloader.dataset.evaluate( File "/root/autodl-fs/SODA-A/mmrotate/mmrotate/datasets/sodaa.py", line 412, in evaluate merged_results = self.merge_det(results, nproc=nproc) File "/root/autodl-fs/SODA-A/mmrotate/mmrotate/datasets/sodaa.py", line 268, in merge_det dets, segms = results ValueError: not enough values to unpack (expected 2, got 0)
> 
> ### Additional information
> _No response_
