### ISSUE TITLE
Where are sodaa_val.json and sodaa_test.json files?

### ISSUE THREAD

**Issue by MandyDongrs** [shaunyuan22/SODA-mmrotate#5]
### Model/Dataset/Scheduler description

Under data/sodaa/split_configs directory, I only find sodda_train.json. Is the configuration of val and test the same as train ( except for the path settings) ? Or could you provide the sodaa_val.json and sodaa_test.json files, as you mentioned in the data structure of sodaa/readme?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by Elendil-Q** [comment]
应该是跟mmrotate的dota处理一样，三个json的内容除了路径其他都是一样的吧。

**Comment by shaunyuan22** [comment]
just replace the key `mode` from `train` to `val` and run the split script, you will get the sub-images and corresponding annotations about val-set, likewise for test-set.
