### ISSUE TITLE
[Docs] 

### ISSUE THREAD

**Issue by GDragon986** [shaunyuan22/SODA-mmrotate#9]
### Branch

master branch  https://mmrotate.readthedocs.io/en/latest/

### 📚 The doc issue

请问一下在Preparing SODA-A Dataset时ata
│   ├── sodaa
│   │   ├── sodaa_split.py
│   │   ├── split_configs
│   │   │   ├── split_train.json
│   │   │   ├── split_val.json
│   │   │   ├── split_test.json
split_train.json,split_val.json.split_test.jso这三个文件怎么获取的

**Comment by shaunyuan22** [comment]
See `tools/data/sodaa/split_configs` for `split_train.json`, and you can achieve `split_val.json` and `split_test.json` by changing the corresponding keywords.

**Comment by GDragon986** [comment]
> See `tools/data/sodaa/split_configs` for `split_train.json`, and you can achieve `split_val.json` and `split_test.json` by changing the corresponding keywords.

  I know how to solve this problem,Thank you
